### PR TITLE
Update Sunken Treasure to 1.14

### PR DESCRIPTION
**Pull request by alluet**
Updated the Sunken Treasure module to use new Minecraft 1.14 technology to optimize execution of the module. Reorganized `pulse_check` to avoid NBT serialization unless a player has mined `minecraft:sand` and is deep enough underwater for the module to activate.

The new Minecraft 1.14 loot table features have allowed several optimizations to be made to Sunken Treasure. First of all, rather than serializing player NBT multiple times to check the enchantments of the player's mainhand tool, and then comparing portions of entity UUIDs to determine whether treasure is found, the module now uses a specialized loot table: `sunken_treasure:function/treasure_type`. This loot table then decides whether the treasure is an item, squid, or guardian at the same rates as in the 1.13 version of the module. Additionally, all item treasure drops are spawned from a loot table now: `sunken_treasure:item_treasure` (or, if SCUBA Gear is installed, `sunken_treasure:item_treasure_scuba`).

Just like in the 1.12 and 1.13 versions of the module, the Sunken Treasure module for Minecraft 1.14 will delete the `minecraft:sand` item if the treasure spawned is an item (rather than a squid or guardian). This requires a second NBT serialization of the `minecraft:sand` item (the first is in `pulse_check`).

Feel free to ask questions about anything that this updated module does, as it is using some brand new technology, such as loot table-based item comparison (which has been found by the command community to be more efficient than doing the same with NBT and the scoreboard).

### CODE REVIEW

**Comment by alluet** [comment]
This is not possible while perfectly preserving drop rates from the 1.13 version of Sunken Treasure. `sunken_treasure:item_treasure_scuba` changes the rates of the leather boots and "Waders" compared to `sunken_treasure:item_treasure`.

You did give me an idea though; there could be a shared loot table referenced by both `sunken_treasure:item_treasure` and `sunken_treasure:item_treasure_scuba`.

**Comment by sparks0** [comment]
Looks good, had a quick test with Blue and I see Misode also left a review!

**Comment by misode** [comment]
@alluet This has some conflicts still

**Comment by Bluefire-610** [comment]
@misode We're resolving the conflicts, merge incoming shortly.

**Pull request merged**
