### PR TITLE
Add a Better Armor Stand "Upgrade"

### PR DESCRIPTION
**Pull request by TheRedKeks**
It adds a book which can do many precised changes on how armor stands lokk and behave. It fully works in survival without op permissions.

### CODE REVIEW

**Comment by Kroppeb** [comment]
Could you give a description of what you added?

**Comment by BluePsychoRanger** [comment]
Don't use the knowledge book as a crafting recipe; link it to use the Custom Crafters module (check the standard crafting module if you don't know how to add a recipe)

**Comment by TheRedKeks** [comment]
I tried but i cant get it to work.

**Comment by TheRedKeks** [comment]
And i have to activate the trigger for the player so how sould i do this?

**Comment by sparks0** [comment]
This module is using the beta standard for the clocking system (old scoreboard and fake player names) which means it won't work with Gamemode 4. It also shouldn't use Minecraft crafting tables for the book recipe. You can look at Heart Canisters for an example of how to interface the custom crafters with your module. A description of exactly what the player does to use this in survival is required too.

**Comment by TheRedKeks** [comment]
Ok and where can i find the new clock systhem?

**Comment by sparks0** [comment]
Testing direct replying...

    On Saturday, 24 November 2018, 13:18:50 GMT, TheRedKeks <notifications@github.com> wrote:  
 
 
Ok and where can i find the new clock systhem?

**Comment by sparks0** [comment]
> Ok and where can i find the new clock systhem?

Take a look at any module in the master git. There's a template pack there too which should get you started.

**Comment by TheRedKeks** [comment]
I think i have built it from this template pack but i will check

**Pull request closed without merging**
