### PR TITLE
Actually fixes #269 for Mysterious Midnights

### LINKED ISSUE #269: Mysterious Midnights item doesn't get consumed correctly
### Expected Behavior
When a bone, rotten flesh or slime ball spawns its corresponding mob, it removes the item.

### Current Behavior
The item isn't killed, causing mobs to be continuously spawned. This can cause massive lag problems.

### Steps to Reproduce
1. Wait for a mysterious midnight, or force one by setting the time
2. Drop a bone, rotten flesh or slime ball on the ground
3. Notice a mob spawns, but the item is still there

### Environment
This happens in 1.14.4 on the Public Server V

### PR DESCRIPTION
**Pull request by Kroppeb**
I'm a dummy dum dum

### CODE REVIEW

**Comment by Bluefire-610** [comment]
Metallurgy? More like mysterious midnights

**Comment by Kroppeb** [comment]
*cough*

**Comment by Kroppeb** [comment]
*cough*

**Comment by Kroppeb** [comment]
Let's just ignore the force push and the PR renaming

**Pull request merged**
