### PR TITLE
Desire Lines: Add Celaro Shamir

### PR DESCRIPTION
**Pull request by Luewd**
Celaro is a new type of Aluminium Band that can be placed on boots, included in the Desire Lines module when loaded alongside Metallurgy. When applied to the player's boots, the Celaro shamir will simply suppress the the effects of Desire Lines, just like the Boots of Ostara. There is also a fun easter egg suggested by Bloo if you stand in tall flowers while wearing Celaro boots.

### CODE REVIEW

**Review by Bloo-dev — COMMENTED** [review]
Shamir names usually follow a latinesque naming scheme, so we may want to reconsider the name. Provided we find a good onr that doesn't feel forced.

**Comment by ToffeeMax** [comment]
> Shamir names usually follow a latinesque naming scheme, so we may want to reconsider the name. Provided we find a good onr that doesn't feel forced.

If a suggestion is wanted -- a play on "invisible" comes to mind -- which works as Caecus

**Comment by Luewd** [comment]
The shamir is now named Celaro instead of Delicate as suggested in #module-discussion on the discord.

**Review by Bloo-dev — APPROVED** [review]
Tested and reviewed.

**Pull request merged**
