### PR TITLE
Mountaineering: fix NBT not being saved when crafting new skis and crampons

### PR DESCRIPTION
**Pull request by AdequateUsername**
NBT of existing iron/chainmail boots were not previously saved when crafting skis/crampons, despite that being desired behaviour. This PR fixes that.

### CODE REVIEW

**Comment by EpyonProjects** [comment]
Tested in singleplayer, looks good!

**Comment by misode** [comment]
This has already been fixed in the 1.20.5 update, I think it'll be best to merge this with the future `ver/1.20` branch

**Comment by misode** [comment]
I don't think anyone has tested this yet

**Review by misode — APPROVED** [review]
I'm a bit confused why this works, but I tested and everything seems to work...

**Pull request merged**
