### PR TITLE
Add Private Lockers

### PR DESCRIPTION
**Pull request by BluePsychoRanger**
Adds a way to lock containers

https://docs.google.com/document/d/1pXnAD8dYIIxYY-hCF7Tg7PkbvxOY7tQiWZby277Kzmw/edit?usp=sharing

### CODE REVIEW

**Comment by Bluefire-610** [comment]
I like the idea of this.
Back in 1.8 I tried to create somthing very similar based on a scoreboard ID system, but it had too many flaws.
Some of those were:
- it is still possible to break the container
- making it unbreakable is a bad idea

Personally, I don't mind if these locked containers can still be broken. It's more about feeling secure rather than being secure.

One small thing I'd prefer is having the player craft the lock onto the container. Throwing stuff onto things just feels outdated to me but Sparks, and possible Special, would disagree.

**Comment by BluePsychoRanger** [comment]
> One small thing I'd prefer is having the player craft the lock onto the container. Throwing stuff onto things just feels outdated to me but Sparks, and possible Special, would disagree.

Do you mean something similar to the piston pushing the item into the chest or right clicking the chest with the lock? Both are possible but the latter requires a player score check every tick.

**Comment by Bluefire-610** [comment]
> > One small thing I'd prefer is having the player craft the lock onto the container. Throwing stuff onto things just feels outdated to me but Sparks, and possible Special, would disagree.
> 
> Do you mean something similar to the piston pushing the item into the chest or right clicking the chest with the lock? Both are possible but the latter requires a player score check every tick.

Neither, I'd suggest renaming the lock item in an anvil and then crafting that lock with the container of choice in a custom crafter

**Comment by BluePsychoRanger** [comment]
Oh right, so I mentioned this on discord when I showed it off, but you can't go from name component to Lock component because Name uses JSON while Lock only uses text strings. This means that a lock named "ABCDE" would turn into a locked container with the lock "{"text":"ABCDE"}"

**Comment by Bluefire-610** [comment]
Oh I see. Well that's inconvenient.

**Comment by BluePsychoRanger** [comment]
Yeah, I know. My initial idea was to make a simple module where you just name a lock and lock the chest. Then I had to get into book and quill cuz that's the only way I can think of to have a text component that's not JSON

**Comment by sparks0** [comment]
What does the system do if the text in the book is over the character limit?

**Comment by sparks0** [comment]
> Oh right, so I mentioned this on discord when I showed it off, but you can't go from name component to Lock component because Name uses JSON while Lock only uses text strings. This means that a lock named "ABCDE" would turn into a locked container with the lock "{"text":"ABCDE"}"

Does this still apply in 1.15 with the new storage command?

**Comment by misode** [comment]
> Does this still apply in 1.15 with the new storage command?

Yes it still does. We would need string manipulation to convert `{"text":"ABCDE"}` into `ABCDE`

**Comment by SandSander** [comment]
**This module idea is quite nice!**
but i think it is still in old version?

**Comment by SandSander** [comment]
This module should actually be closed because it is an old version?

**Comment by Bloo-dev** [comment]
I'm closing this as it was developed for an outdated version of Minecraft

**Pull request closed without merging**
