### PR TITLE
Add wolf variants to balloon animals

### PR DESCRIPTION
**Pull request by catter1**
## Variants
Wolf variants are now supported. When a wolf is picked, one of the 9 varaints are chosen at random. This is done by creating a custom `init_wolf` function that is a duplicate of `init_animal`, but adds the random selection. This could be simplified by using macros, but I felt more comfortable with this implementation for now.

As an extra note: Currently the wolf variants are hardcoded in the `generate.py`. Can easily be moved to a csv if needed.

## Changelog Checklist
- [x] ~~Add armadillo to animal pool~~
- [x] Create custom wolf init function to support variants

### CODE REVIEW

**Comment by misode** [comment]
Oh rip, Sheepe had also added Armadillos in #1039

**Comment by catter1** [comment]
Note: #1039 also adds the Armadillos to the animal pool. This was done after I had done the change myself (but before I made the PR). For merging, feel free to scrap my commit on that specific part, or maybe selectively merge just the names.

**Comment by misode** [comment]
FYI: in the future you should use a separate branch than `master`, so you can create multiple PRs without constantly resetting your own master branch

**Comment by catter1** [comment]
Yeah, just realized that mistake 😅 Will be doing that for the next PRs

**Comment by misode** [comment]
I reverted the armadillo addition, hopefully to help deal with the merge conflict, and to give #1039 full control on the names

**Review by misode — CHANGES_REQUESTED** [review]
I tested this in-game, and it seems like wolfs don't add the corresponding trade option to the trader villager.

**Comment by catter1** [comment]
Should be fixed now with c59ee31, at least with my own testing

**Review by catter1 — COMMENTED** [review]
I initially thought common animals were supposed to be more common, but then a brief discussion in the discord informed me that it *is* supposed to be this way. Trader should be offering the player the rarer animals more often, since the common ones are "useless"

**Review by misode — APPROVED** [review]
Works now!

**Pull request merged**
