### PR TITLE
Despawn Indicator: A small module for showing when items despawn.

### PR DESCRIPTION
**Pull request by magierpichu**
Hi, I had a little idea for a module, so I thought I'd get myself comfy with the new system.
Anyway, this module will create a particle effect depending on how much time there's left before the item despawns. Yellow for 30, red for ten and black for three seconds.

PS. I'm sorry if this is the wrong way to do it. I'm still getting used to github.

### CODE REVIEW

**Comment by SpiderRobotMan** [comment]
I think this is a neat idea, but I'm not sure it's enough of a feature to be a whole module.

**Comment by magierpichu** [comment]
Maybe not, but other than items, I don't know any entities that would benefit from having a clear despawn indication. I just don't understand why something like this isn't already in the game, as it is really frustrating to see your items disappear in front of you. Anyway, if you ever find a spot for it in a broader datapack, I would feel honored.

**Comment by Bluefire-610** [comment]
I agree with spider, it seems a bit thin for it's own module and "I have this concept, let's look for things we can apply it to to make it module-sized" never turned out great. 
On the other hand, the idea is neat. maybe we could try to get a flashing behavior like other games have. This is something to keep in mind for sure.

**Comment by sparks0** [comment]
We have a module that just makes bats  explode. I don't think simple is necessarily bad and I think the problem being addressed here is a real one.

**Comment by magierpichu** [comment]
I decided to also make it work with arrows and I changed the particle effects to show yellow particles when there are 15 seconds left and red when there are only 5 seconds left.

**Comment by alluet** [comment]
Clocking standard is still out of date, and I have an interesting idea to make the animation look a bit cooler. Might rewrite this from scratch.

**Pull request closed without merging**
