### PR TITLE
Module Icon Update

### PR DESCRIPTION
**Pull request by BluePsychoRanger**
- Update all Icons to 512x512 to allow the website to extract from Github rather than rely on external (easily outdated) database
- Update some Icons that Hozz revamped
- Add credit for all icon designs
- changed "Creator" to "Creators" in the credits section if there are more than one person listed
- fixed some instances of "accidentalgames" and "Bluefire"

### CODE REVIEW

**Review by Bloo-dev — APPROVED** [review]
I've manually checked out all files and corrected some minor crediting errors. This seems fine.
Waiting on @sparks0 to confirm that the current website can handle this.

**Review by misode — CHANGES_REQUESTED** [review]
The current site actually uses SVGs for module icons. It would be much better to store both a pack.png (with the maximum size Minecraft can use) and a pack.svg here for each module.

**Comment by BluePsychoRanger** [comment]
> The current site actually uses SVGs for module icons. It would be much better to store both a pack.png (with the maximum size Minecraft can use) and a pack.svg here for each module.

True, but I'd like to point out the the current implementation of SVGs has some weird errors, causing lines that shouldn't be visible (e.g. Tower Structures, Ziprails). This is because the SVG has overlapping objects that are the same color, but when viewed on the (new) website, it doesn't correctly flatten the layers. If this can't be fixed, I think using the 512x512 images is the best option. 

Not using SVGs in the data packs will also allow other people to submit module icons without needing an SVG creating software. Though it will likely be converted to an SVG anyways in the future, so this isn't much of an issue.

**Comment by BluePsychoRanger** [comment]
pack.svg has been added to all the modules now, this is ready to be used on the website

**Comment by sparks0** [comment]
This looks all good to me, assuming we've done a JSON validation check on the pack.mcmetas? Idk if our auto-check does that?

**Review by sparks0 — APPROVED** [review]

**Review by misode — APPROVED** [review]

**Pull request merged**
