### PR TITLE
Added Invisible and Visible Tags

### PR DESCRIPTION
**Pull request by ToffeeMax**
I believe this was an old feature - but if not:

- Type "invisible" in Book to make armour stand invisible
- Type "visibile"in book to make armour stand visible
- Was created to not have to use particles pack to make invisible and have a particle

### CODE REVIEW

**Comment by iGalaxyYT** [comment]
I've been wanting this for so long 👀

**Comment by sparks0** [comment]
Issue with this is the "invisible armorstands glow when holding a blank book" is a feature of particles pack not better armour stands so it would be possible to completely lose your stands. The glowing feature would need to be moved to the base. Otherwise I'd be ok with this.

**Comment by ToffeeMax** [comment]
@sparks0  - I moved the functionality from particles pack to better armor_stands as per your request :)

**Comment by ToffeeMax** [comment]
@sparks - Apologies, should have actually thought instead of bringing over old functionality. Has been tested and works. Only gives to armor_stands with nbt tag "Invisible:1b" and works with any written book

**Comment by ToffeeMax** [comment]
@misode - It made sense. Because it is annoying having to empty the book to then retype

**Comment by AndanteDevs** [comment]
I know 1.14 GM4 is not supported yet, but you can't have an empty book in the new update after you've written in it before. It simply won't let you. If players get used to this, it won't be an issue, as such, but it's better to set the format now instead of confusing players when things don't work later.

**Pull request merged**
