### PR TITLE
Update Metallurgy to 1.14

### PR DESCRIPTION
**Pull request by misode**
Initial changes to make metallurgy work in 1.14. This does not use any new 1.14 features to improve efficiency yet.

* use `#minecraft:signs` in conduction block tag
* all lore changed to use text components
* tnt exploding within 16 ticks of each other now works correctly
* use `Age:0s,PickupDelay:10s` instead of `Age:1s,PickupDelay:9s` (I'm not sure why)
* uncomment the repair function call

### CODE REVIEW

**Comment by misode** [comment]
I simplified the band summoning drastically. Shamir expansions will only need one function with only the bare minimum:
```mcfunction
summon item ~ ~ ~ {Tags:[gm4_ml_band],Item:{id:"minecraft:player_head",Count:1b,tag:{gm4_metallurgy:{stored_shamir:"arborenda"},display:{Lore:['{"text":"Arborenda","color":"gray","italic":false}']}}}}
```
The base module will apply all the other tags for creating the shamir.

**Comment by misode** [comment]
Simplified and centralized the code for smooshing. Most operations are moving around strings in the NBT. However there is one thing that the expansions have to do, which is check if it is a valid item to put the shamir on. The expansion has these functions which make sure that the score gets set to one whenever the shamir and item type is a valid combination.
```mcfunction
execute if entity @e[type=item,tag=gm4_ml_source,dx=0,nbt={Item:{tag:{gm4_metallurgy:{stored_shamir:"arborenda"}}}}] run function arborenda_shamir:mark_item_validity
```
```mcfunction
execute unless score valid_item gm4_ml_data matches 1 store success score valid_item gm4_ml_data if entity @s[nbt={Item:{id:"minecraft:diamond_axe"}}]
execute unless score valid_item gm4_ml_data matches 1 store success score valid_item gm4_ml_data if entity @s[nbt={Item:{id:"minecraft:iron_axe"}}]
execute unless score valid_item gm4_ml_data matches 1 store success score valid_item gm4_ml_data if entity @s[nbt={Item:{id:"minecraft:golden_axe"}}]
execute unless score valid_item gm4_ml_data matches 1 store success score valid_item gm4_ml_data if entity @s[nbt={Item:{id:"minecraft:stone_axe"}}]
execute unless score valid_item gm4_ml_data matches 1 store success score valid_item gm4_ml_data if entity @s[nbt={Item:{id:"minecraft:wooden_axe"}}]
```

**Comment by Bluefire-610** [comment]
What's the status on this? We want to release a metallurgy video soon-ish, do you want us to finish this update for you?

**Comment by misode** [comment]
@Bluefire-610 The base of metallurgy qnd the interaction with the shamirs is basically done. The thing to do now is translation, custom model data, and optimizations for the shamirs itself. That last part can potentially be done separately later.

**Comment by Kroppeb** [comment]
I can probably do quite some optimisations once my exams are done.

**Comment by misode** [comment]
The final changes to support GM4_Resources were made. This branch is now ready to be tested and merged.

**Comment by misode** [comment]
What's stopping this from being merged? @sparks0 @Bluefire-610 @SpecialBuilder32

**Comment by sparks0** [comment]
We didn't realize this was done!

**Pull request merged**
