### PR TITLE
Add Soul Glass

### PR DESCRIPTION
**Pull request by BluePsychoRanger**
Adds a new glass type which is created by smelting soul sand in a blast furnace. When placed on top of a beacon, the effects are reversed. 
https://docs.google.com/document/d/1aREQrHd4CkpZM2I9pajyL5oerTAsoTBoRPzObOUMTP4/edit?usp=sharing

Requested by Bloo, created by BPR and Denniss.

### CODE REVIEW

**Comment by misode** [comment]
Please don't commit the `.DS_Store` files

**Comment by BluePsychoRanger** [comment]
> Please don't commit the `.DS_Store` files

OMG I thought I deleted them .-.

**Comment by Bloo-dev** [comment]
This will look great with 1.16's soul particles!

**Comment by Bloo-dev** [comment]
Looking good. However, there's one bug that needs to be fixed before I can merge  this:
Corrupted beacons with an obstructed beam still emit their corrupted effects.

**Pull request merged**
