### PR TITLE
Add Meme poses pack

### PR DESCRIPTION
**Pull request by misode**
Possible book commands:
* `t-pose`
* `dab`
* `dabbing` (animated)
* `floss`
* `flossing` (animated)

### CODE REVIEW

**Comment by BluePsychoRanger** [comment]
`pack.mcmeta` is missing website/credit information and `default.mcfunction` is empty

**Comment by Bluefire-610** [comment]
Tesset wants poses to not re-add arms.

**Comment by sparks0** [comment]
Or add a sassy wiggle animation. plox. thanks.

**Comment by sparks0** [comment]
This PR has been inactive since the last request for more than 30 days so I'm closing it. You can reply here to have it re-opened when you have changes to push.

**Pull request closed without merging**
