### PR TITLE
Fixes #127

### LINKED ISSUE #127: [Potion Swords] Skeletons spread out when wither-ized, even into nearby blocks
### Expected Behavior
The skeletons should just simply 'turn into' wither skeletons and not move.

### Current Behavior
This is an issue that affects wither skeleton skull farms. When you hit multiple skeletons with the relevant potion sword to turn them into wither skeletons, the newly-created wither skeletons will 'spurt' out, even into adjacent blocks.

### Possible Solution
Create a temporary no collision team, use the `Team` nbt tag while summoning the transformed wither skeletons and then remove them from that team.

### Steps to Reproduce
1. Summon multiple skeletons in one place.
2. Hit them holding a golden sword with a poison II potion in your inventory.
3. Watch them, unless it (rarely) doesn't happen, spurt out. If caged, they'll suffocate in the blocks.

### Environment
Multiplayer on GM4 PSV
All modules installed, of course.

### PR DESCRIPTION
**Pull request by AndanteDevs**
Ref. #127

### CODE REVIEW

**Comment by AndanteDevs** [comment]
There are two unnecessary commits here, I would recommend squashing when merging. They were created in my testing.

**Comment by misode** [comment]
This pull request modifies some parts of heart canisters and CONTRIBUTING.md

**Comment by AndanteDevs** [comment]
> This pull request modifies some parts of heart canisters and CONTRIBUTING.md

Those will be from when I pulled the new master branch.

**Comment by misode** [comment]
They are still unnecessary changes and those file changes need to be removed. Make a new pull request or pull from upstream master.

**Comment by AndanteDevs** [comment]
Unnecessary changes removed in #129

**Pull request closed without merging**
