### PR TITLE
Add Midnight Menaces 1.15

### PR DESCRIPTION
**Pull request by BluePsychoRanger**
Features are all the same as the 1.14 version which was approved but never merged. I just updated for 1.15.

### CODE REVIEW

**Comment by BluePsychoRanger** [comment]
> Same features as #220 and #211, which were approved but never merged for some reason. Should we close those as supporting old versions is, wierd?

Yeah, that sounds fine

**Comment by Bloo-dev** [comment]
The magic worked!

**Comment by SandSander** [comment]
Has anyone tested this module yet?

**Comment by Bloo-dev** [comment]
We're pushing this onto Public Server 6 for survival testing.

**Comment by Bloo-dev** [comment]
We've tried putting this on PS6 for a playtest but got some errors:
`Couldn't read function tag list gm4_mysterious_midnights:common_expansion from gm4_mysterious_midnights:tags/functions/common_expansion.json in data pack gm4_midnight_menaces
com.google.gson.JsonParseException: Unknown value 'sandy_husks:setup'

Couldn't read function tag list gm4_nightmare_nights:nightmare_night_expansion from gm4_nightmare_nights:tags/functions/nightmare_night_expansion.json in data pack gm4_midnight_menaces
com.google.gson.JsonParseException: Unknown value 'enlarging_phantoms:setup'

Couldn't read function tag list gm4_mysterious_midnights:rare_expansion from gm4_mysterious_midnights:tags/functions/rare_expansion.json in data pack gm4_midnight_menaces
com.google.gson.JsonParseException: Unknown value 'menacing_goblins:setup'

Couldn't read function tag list gm4_mysterious_midnights:uncommon_expansion from gm4_mysterious_midnights:tags/functions/uncommon_expansion.json in data pack gm4_midnight_menaces
com.google.gson.JsonParseException: Unknown value 'enlarging_phantoms:setup'`

**Comment by BluePsychoRanger** [comment]
@Bloo-dev the changes have been made and I tested each night and they all work as far as I can tell. Only thing that may need tweaking is spawn rates of the mobs.

**Comment by BluePsychoRanger** [comment]
We're now in 1.16. MM and this Module will be rewritten in the future

**Pull request closed without merging**
