### PR TITLE
Add Equivalent Exchange

### PR DESCRIPTION
**Pull request by BluePsychoRanger**
Overhauled version of Equivalent Exchange

Documentation:
https://docs.google.com/document/d/1DyAEc_BrxJElrUr-ToxOo_sLrqjm01h6rGfZFVp2_dw/edit?usp=sharing

### CODE REVIEW

**Comment by sparks0** [comment]
I've seen you getting feedback and making changes for this recently. Are you still touching this up or is it ready for review?

Also please remove .gitignore from your PR :)

**Comment by Kroppeb** [comment]
Just a note on your gitignore, I think you can make it ignore all of the same file type at once

**Comment by BluePsychoRanger** [comment]
@sparks0 
I'm still touching it up. I've gotten some feedback, but if you could fill out this form with what you think, it'd be helpful. https://goo.gl/forms/U4kRDPHFoahnE1P23 also, I'll remove the .gitignore from the PR, I'm still getting used to GitHub :p

**Comment by Nathan22211** [comment]
glad to see your updating it. LLgaming updated the module to 1.12 2-3 years ago. hey sparks maybe this could be viable for the website

**Comment by ToffeeMax** [comment]
The focus is for 1.13 at the moment, so - it would be very unlikely

**Comment by Nathan22211** [comment]
i ment BPR's datapack not that 2yr old module

**Comment by sparks0** [comment]
We have decided to stop accepting modules for 1.13. Closing this PR (your 1.14 submission is still open)

**Pull request closed without merging**
